/* eslint-disable */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ProgressRouteImport } from "./routes/progress";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as MealsRouteImport } from "./routes/meals";
import { Route as AddRouteImport } from "./routes/add";
import { Route as IndexRouteImport } from "./routes/index";

const ProgressRoute = ProgressRouteImport.update({
  id: "/progress",
  path: "/progress",
  getParentRoute: () => rootRouteImport,
});
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
});
const MealsRoute = MealsRouteImport.update({
  id: "/meals",
  path: "/meals",
  getParentRoute: () => rootRouteImport,
});
const AddRoute = AddRouteImport.update({
  id: "/add",
  path: "/add",
  getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});

const rootRouteChildren = {
  IndexRoute,
  AddRoute,
  MealsRoute,
  ProfileRoute,
  ProgressRoute,
};

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren);
